### ISSUE TITLE
可以关注一下清华CBICR组的一些工作

### ISSUE THREAD

**Issue by lyh983012** [LarryDong/EventCameraGroupsCN#1]
数据集部分
CIFAR10-DVS DVS实拍显示屏上图像运动：https://www.frontiersin.org/articles/10.3389/fnins.2017.00309/full
下载：https://figshare.com/articles/dataset/CIFAR10-DVS_New/4724671/2
ES-ImageNet 很trival的转换，大概和DVS关系不大：https://www.frontiersin.org/articles/10.3389/fnins.2021.726582/full
下载：https://cloud.tsinghua.edu.cn/d/94873ab4ec2a4eb497b3

DVS+SNN:
LIAF，做了些DVS分类的实验：https://ieeexplore.ieee.org/document/9429228
DashNet，SNN+ANN 混合DVS追踪：https://arxiv.org/pdf/1909.12942.pdf

**Comment by LarryDong** [comment]
感谢！Check [this commit](https://github.com/LarryDong/EventCameraGroupsCN/commit/483a2ffd4372671623689f6b6044eb62af8f99e3)

**Comment by LarryDong** [comment]
或许有哪位朋友可以提供下实验室主页，或施老师的个人主页。我找了半天没找到，谢谢~

**Comment by lyh983012** [comment]
话说我记得西交的组也有做dvs+snn

**Comment by lyh983012** [comment]
西交也有组在做DVS+SNN，我只记得这篇了因为我参与了一丁点，但是应该有别的
https://openaccess.thecvf.com/content/ICCV2021/html/Yao_Temporal-Wise_Attention_Spiking_Neural_Networks_for_Event_Streams_Classification_ICCV_2021_paper.html

然后深圳的鹏城实验室应该也有挺多工作的，具体我忘记了。。但我知道他们最近做了一个非常大规模的DVS数据集

**Comment by lyh983012** [comment]
> 或许有哪位朋友可以提供下实验室主页，或施老师的个人主页。我找了半天没找到，谢谢~

我们实验室的主页似乎挂了，施老师似乎也没维护自己的主页也没有scholar之类的……

**Comment by lyh983012** [comment]
找到了，鹏城的： https://sites.google.com/view/xiaowanghomepage/

**Comment by LarryDong** [comment]
cool

**Comment by DachunKai** [comment]
> 数据集部分 CIFAR10-DVS DVS实拍显示屏上图像运动：https://www.frontiersin.org/articles/10.3389/fnins.2017.00309/full 下载：https://figshare.com/articles/dataset/CIFAR10-DVS_New/4724671/2 ES-ImageNet 很trival的转换，大概和DVS关系不大：https://www.frontiersin.org/articles/10.3389/fnins.2021.726582/full 下载：https://cloud.tsinghua.edu.cn/d/94873ab4ec2a4eb497b3
> 
> DVS+SNN: LIAF，做了些DVS分类的实验：https://ieeexplore.ieee.org/document/9429228 DashNet，SNN+ANN 混合DVS追踪：https://arxiv.org/pdf/1909.12942.pdf

显示屏上拍的event数据集，会不会缺少实际场景depth等信息。

**Comment by LarryDong** [comment]
> 显示屏上拍的event数据集，会不会缺少实际场景depth等信息。

应该是没有深度信息的，还是看具体的目的。
这个issue和repo不探讨具体的数据集/论文问题，请移步相关数据集或联系作者讨论。

**Comment by lyh983012** [comment]
> 

会，而且还会引入LED闪烁噪声之类的东西，所以是一个不好的选择，现在DVS实拍场景的数据集很多了

**Comment by lyh983012** [comment]
> > 数据集部分 CIFAR10-DVS DVS实拍显示屏上图像运动：https://www.frontiersin.org/articles/10.3389/fnins.2017.00309/full 下载：https://figshare.com/articles/dataset/CIFAR10-DVS_New/4724671/2 ES-ImageNet 很trival的转换，大概和DVS关系不大：https://www.frontiersin.org/articles/10.3389/fnins.2021.726582/full 下载：https://cloud.tsinghua.edu.cn/d/94873ab4ec2a4eb497b3
> > DVS+SNN: LIAF，做了些DVS分类的实验：https://ieeexplore.ieee.org/document/9429228 DashNet，SNN+ANN 混合DVS追踪：https://arxiv.org/pdf/1909.12942.pdf
> 
> 显示屏上拍的event数据集，会不会缺少实际场景depth等信息

会，而且还会引入LED闪烁噪声之类的东西，所以是一个不好的选择，现在DVS实拍场景的数据集很多了。
